export default {
  backgroundColor: "#FFF",
  blackColor: "#262626",
  greyColor: "#5B5B5B",
  lightGreenColor: "#A6E971",
  pastelGreenColor: "#E5F4D5",
  greenColor: "#26A211",
  darkGreenColor: "#9FDBB0",
  darkGreyColor: "#999",
  pastelGreyColor: "#ECECEC",
  lightGreyColor: "#b2b2b2",
  moreLightGreyColor: "#ebebeb",
  redColor: "#ED4956",
  blueColor: "#3897f0",
  darkBlueColor: "#003569",
  regularFont: "nanumSquareRegular",
  boldFont: "nanumSquareBold",
  withShadow: {
    backgroundColor: "#FFF",
    borderWidth: 0,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 1,
    shadowOffset: {
      height: 2.5,
      width: 2.5,
    },
  },
};
