export default {
  backgroundColor: "#FFF",
  blackColor: "#262626",
  greyColor: "#090909",
  lightGreenColor: "#b1fbb1",
  darkGreyColor: "#999",
  lightGreyColor: "#b2b2b2",
  moreLightGreyColor: "#ebebeb",
  redColor: "#ED4956",
  blueColor: "#3897f0",
  darkBlueColor: "#003569",
  regularFont: "nanumSquareRegular",
  boldFont: "nanumSquareBold",
  withShadow: {
    backgroundColor: "#FFF",
    borderWidth: 0,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 1,
    shadowOffset: {
      height: 2.5,
      width: 2.5,
    },
  },
};
